language: go

services:
  - docker

go:
  - 1.8

install:
  - go get -v -t ./...
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/onsi/gomega
  - go get -u github.com/golang/lint/golint
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - for d in $(go list ./... | grep -v vendor); do go vet $d; done
  - for d in $(go list ./... | grep -v vendor); do golint $d; done
  - ginkgo *

after_success:
  - bash <(curl -s https://codecov.io/bash)
